services:
  db:
    image: mariadb:11.2
    environment:
      MARIADB_ROOT_PASSWORD: epitech
      MARIADB_DATABASE: studydb
    volumes:
      - db-data:/var/lib/mysql
      - ./backend/studydb.sql:/docker-entrypoint-initdb.d/studydb.sql
    networks:
      - back-tier
    ports:
      - 3307:3306
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-pepitech",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend/
    ports:
      - "8081:8081"
    volumes:
      - ./backend/music/:/app/music:ro
    environment:
      - MUSIC_DIR=/app/music/
      - DATABASE_URL=mysql://root:epitech@db:3306/studydb
      - SECRET=iusearchbtw
    networks:
      - back-tier
      - front-tier
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  web:
    build: ./frontend/
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - front-tier

volumes:
  db-data:

networks:
  back-tier:
  front-tier:
