CREATE DATABASE IF NOT EXISTS studydb;
USE studydb;

GRANT ALL PRIVILEGES ON studydb.* TO 'root'@'%' IDENTIFIED BY 'epitech';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS user (
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    email VARCHAR(255) NOT NULL,
    pass VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(255) NOT NULL,
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS todo (
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dtime TIMESTAMP NOT NULL,
    user_id INTEGER UNSIGNED NOT NULL,
    status VARCHAR(255) DEFAULT 'not started',
    FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE streaks (
    user_id INTEGER UNSIGNED NOT NULL PRIMARY KEY,
    current_streak INTEGER UNSIGNED NOT NULL DEFAULT 1,
    longest_streak INTEGER UNSIGNED NOT NULL DEFAULT 1,
    last_active DATE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);
